export interface PlatformPreset {
  platform: string;
  label: string;
  placeholder: string;
  urlPrefix: string;
  iconName: string;
  color: string;
  badgeBg: string;
}

export const SOCIAL_PLATFORMS: PlatformPreset[] = [
  {
    platform: 'instagram',
    label: 'Instagram',
    placeholder: 'https://instagram.com/arjunfilms or @arjunfilms',
    urlPrefix: 'https://instagram.com/',
    iconName: 'instagram',
    color: '#E4405F',
    badgeBg: 'bg-gradient-to-tr from-[#f09433] via-[#dc2743] to-[#bc1888]',
  },
  {
    platform: 'youtube',
    label: 'YouTube Channel',
    placeholder: 'https://youtube.com/@arjunfilms',
    urlPrefix: 'https://youtube.com/@',
    iconName: 'youtube',
    color: '#FF0000',
    badgeBg: 'bg-[#FF0000]',
  },
  {
    platform: 'whatsapp',
    label: 'WhatsApp Direct Chat',
    placeholder: 'https://wa.me/919876543210 or 919876543210',
    urlPrefix: 'https://wa.me/',
    iconName: 'message-circle',
    color: '#25D366',
    badgeBg: 'bg-[#25D366]',
  },
  {
    platform: 'facebook',
    label: 'Facebook Page',
    placeholder: 'https://facebook.com/arjunfilms',
    urlPrefix: 'https://facebook.com/',
    iconName: 'facebook',
    color: '#1877F2',
    badgeBg: 'bg-[#1877F2]',
  },
  {
    platform: 'twitter',
    label: 'X (formerly Twitter)',
    placeholder: 'https://x.com/arjunfilms or @arjunfilms',
    urlPrefix: 'https://x.com/',
    iconName: 'twitter',
    color: '#000000',
    badgeBg: 'bg-black dark:bg-white/90',
  },
  {
    platform: 'linkedin',
    label: 'LinkedIn Page',
    placeholder: 'https://linkedin.com/company/arjunfilms',
    urlPrefix: 'https://linkedin.com/in/',
    iconName: 'linkedin',
    color: '#0A66C2',
    badgeBg: 'bg-[#0A66C2]',
  },
  {
    platform: 'pinterest',
    label: 'Pinterest Inspiration',
    placeholder: 'https://pinterest.com/arjunfilms',
    urlPrefix: 'https://pinterest.com/',
    iconName: 'image',
    color: '#BD081C',
    badgeBg: 'bg-[#BD081C]',
  },
  {
    platform: 'behance',
    label: 'Behance Portfolio',
    placeholder: 'https://behance.net/arjunfilms',
    urlPrefix: 'https://behance.net/',
    iconName: 'palette',
    color: '#1769FF',
    badgeBg: 'bg-[#1769FF]',
  },
  {
    platform: 'spotify',
    label: 'Spotify Playlist',
    placeholder: 'https://open.spotify.com/playlist/...',
    urlPrefix: 'https://open.spotify.com/',
    iconName: 'music',
    color: '#1DB954',
    badgeBg: 'bg-[#1DB954]',
  },
  {
    platform: 'threads',
    label: 'Threads Profile',
    placeholder: 'https://threads.net/@arjunfilms',
    urlPrefix: 'https://threads.net/@',
    iconName: 'at-sign',
    color: '#000000',
    badgeBg: 'bg-black',
  },
  {
    platform: 'telegram',
    label: 'Telegram Channel',
    placeholder: 'https://t.me/arjunfilms',
    urlPrefix: 'https://t.me/',
    iconName: 'send',
    color: '#229ED9',
    badgeBg: 'bg-[#229ED9]',
  },
  {
    platform: 'website',
    label: 'Official Website',
    placeholder: 'https://arjunfilms.com',
    urlPrefix: 'https://',
    iconName: 'globe',
    color: '#e50914',
    badgeBg: 'bg-[#e50914]',
  },
  {
    platform: 'custom',
    label: 'Custom Link',
    placeholder: 'https://...',
    urlPrefix: 'https://',
    iconName: 'link',
    color: '#6366F1',
    badgeBg: 'bg-[#6366F1]',
  },
];

export const AVAILABLE_ICONS = [
  { name: 'sparkles', label: 'Sparkles / Magic' },
  { name: 'camera', label: 'Camera / Photography' },
  { name: 'video', label: 'Video / Cinema' },
  { name: 'film', label: 'Film Reel' },
  { name: 'heart', label: 'Wedding / Heart' },
  { name: 'award', label: 'Award / Trophy' },
  { name: 'star', label: 'Star / Review' },
  { name: 'credit-card', label: 'Payment / Card' },
  { name: 'file-text', label: 'Quotation / Document' },
  { name: 'calendar', label: 'Calendar / Booking' },
  { name: 'map-pin', label: 'Location / Studio' },
  { name: 'phone', label: 'Phone / Call' },
  { name: 'message-circle', label: 'WhatsApp / Chat' },
  { name: 'mail', label: 'Email / Contact' },
  { name: 'globe', label: 'Website / Web' },
  { name: 'shopping-bag', label: 'Shop / Package' },
  { name: 'music', label: 'Music / Playlist' },
  { name: 'users', label: 'Team / Crew' },
  { name: 'shield-check', label: 'Verified / Secure' },
  { name: 'zap', label: 'Instant / Fast' },
];

export const DEFAULT_BIO_DATA = {
  slug: 'arjunfilms',
  studioName: 'Arjun Films & Photography',
  ownerName: 'Arjun Samal',
  tagline: 'Cinematic Weddings • Luxury Portfolios • Commercials',
  bio: 'Capturing unforgettable love stories and timeless wedding cinema across India & destination locations worldwide. Available for 2025–2026 dates.',
  avatar: '/logo.jpeg',
  coverImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
  watermarkUrl: '',
  verified: true,
  phone: '+91 77889 92712',
  whatsapp: '917788992712',
  email: 'arjunphotographyyy@gmail.com',
  location: 'Bhubaneswar, Odisha, India',
  website: 'https://arjunfilms.com',
  gstin: '',
  panNumber: '',
  upiId: '7788992712@upi',
  upiQrCode: '',
  bankName: 'State Bank of India',
  bankAccountNumber: '',
  bankIfsc: '',
  bankAccountName: 'Arjun Photography',
  defaultPaymentTerms:
    '1. 50% advance payment required for date reservation.\n2. 30% payment on the event shoot date.\n3. 20% final balance upon raw previews delivery.',
  socialLinks: [
    {
      id: 'soc_instagram',
      platform: 'instagram',
      label: 'Instagram',
      url: 'https://instagram.com/arjunfilms',
      username: '@arjunfilms',
      icon: 'instagram',
      color: '#E4405F',
      isActive: true,
      order: 1,
      clickCount: 142,
    },
    {
      id: 'soc_youtube',
      platform: 'youtube',
      label: 'YouTube 4K Films',
      url: 'https://youtube.com/@arjunfilms',
      username: '@arjunfilms',
      icon: 'youtube',
      color: '#FF0000',
      isActive: true,
      order: 2,
      clickCount: 98,
    },
    {
      id: 'soc_whatsapp',
      platform: 'whatsapp',
      label: 'WhatsApp Chat',
      url: 'https://wa.me/919876543210',
      username: '+91 98765 43210',
      icon: 'message-circle',
      color: '#25D366',
      isActive: true,
      order: 3,
      clickCount: 215,
    },
    {
      id: 'soc_facebook',
      platform: 'facebook',
      label: 'Facebook',
      url: 'https://facebook.com/arjunfilms',
      username: 'Arjun Films & Photography',
      icon: 'facebook',
      color: '#1877F2',
      isActive: true,
      order: 4,
      clickCount: 64,
    },
    {
      id: 'soc_twitter',
      platform: 'twitter',
      label: 'X (Twitter)',
      url: 'https://x.com/arjunfilms',
      username: '@arjunfilms',
      icon: 'twitter',
      color: '#000000',
      isActive: true,
      order: 5,
      clickCount: 31,
    },
    {
      id: 'soc_linkedin',
      platform: 'linkedin',
      label: 'LinkedIn',
      url: 'https://linkedin.com/company/arjunfilms',
      username: 'Arjun Films Studio',
      icon: 'linkedin',
      color: '#0A66C2',
      isActive: true,
      order: 6,
      clickCount: 19,
    },
    {
      id: 'soc_pinterest',
      platform: 'pinterest',
      label: 'Pinterest Boards',
      url: 'https://pinterest.com/arjunfilms',
      username: '@arjunfilms',
      icon: 'image',
      color: '#BD081C',
      isActive: true,
      order: 7,
      clickCount: 45,
    },
  ],
  customLinks: [
    {
      id: 'cus_1',
      title: '🎬 2025-2026 Wedding Cinema Showreel',
      subtitle: 'Watch our 4K cinematic wedding highlights, teasers & bridal films',
      url: 'https://youtube.com/@arjunfilms',
      icon: 'video',
      thumbnail: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=600&q=80',
      badge: '🔥 Must Watch',
      isHighlighted: true,
      isActive: true,
      order: 1,
      clickCount: 340,
    },
    {
      id: 'cus_2',
      title: '📸 Destination Wedding & Pre-Wedding Portfolio',
      subtitle: 'Browse 500+ curated photo galleries & pre-wedding shoots',
      url: 'https://instagram.com/arjunfilms',
      icon: 'camera',
      thumbnail: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=600&q=80',
      badge: 'Popular',
      isHighlighted: true,
      isActive: true,
      order: 2,
      clickCount: 289,
    },
    {
      id: 'cus_3',
      title: '💍 Check Date Availability & Get Instant Quote',
      subtitle: 'Calculate customized wedding & event photography packages in 2 mins',
      url: '/quotations',
      icon: 'file-text',
      thumbnail: '',
      badge: '⚡ Instant Quote',
      isHighlighted: true,
      isActive: true,
      order: 3,
      clickCount: 182,
    },
    {
      id: 'cus_4',
      title: '💳 Quick Online Advance Payment Portal',
      subtitle: 'Pay token advance & booking deposits via UPI, QR, or NetBanking',
      url: '/payment',
      icon: 'credit-card',
      thumbnail: '',
      badge: 'Verified',
      isHighlighted: false,
      isActive: true,
      order: 4,
      clickCount: 97,
    },
    {
      id: 'cus_5',
      title: '⭐ 5-Star Reviews & Bride Testimonials',
      subtitle: 'Read genuine reviews and recommendations from our 300+ couples',
      url: 'https://google.com',
      icon: 'star',
      thumbnail: '',
      badge: '⭐ 4.9 (300+)',
      isHighlighted: false,
      isActive: true,
      order: 5,
      clickCount: 114,
    },
    {
      id: 'cus_6',
      title: '📍 Studio Locations & Appointment Schedule',
      subtitle: 'Meet our lead cinematographers at Bhubaneswar or Mumbai studio',
      url: 'https://maps.google.com',
      icon: 'map-pin',
      thumbnail: '',
      badge: 'Studio',
      isHighlighted: false,
      isActive: true,
      order: 6,
      clickCount: 52,
    },
  ],
  viewsCount: 1280,
  totalClicks: 1544,
  themeStyle: 'cinematic-dark',
  buttonShape: 'rounded-2xl',
  showShareButton: true,
  showInquiryButton: true,
};
